Code/WebSiteQuanAo1/WebSiteQuanAo/WebSiteQuanAo/WebsiteBanHang/WebsiteBanHang/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebsiteBanHang.Context;
using WebsiteBanHang.Models;
namespace WebsiteBanHang.Controllers
{
    public class CartController : Controller
    {
        WebsiteBanQuanAoEntities2 objWebsiteBanHangEntities = new WebsiteBanQuanAoEntities2();
        // GET: Cart
        public ActionResult Index()
        {
         
            return View((List<CartModel>)Session["cart"]);
        }
      
        public ActionResult AddToCart(int id,int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = objWebsiteBanHangEntities.Product.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiem tra san pham co trong gio hang chua
                int index = isExist(id);
                if (index != -1)
                {
                    //Neu ton tai thi cong them so luong    
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //Neu khong ton tai thi them vao 
                    cart.Add(new CartModel { Product = objWebsiteBanHangEntities.Product.Find(id), Quantity = quantity });
                    //tinh lai so san pham trong gio hang
                    Session["count"]= Convert.ToInt32(Session["count"]) +1;

                }
                // Cập nhật số lượng sản phẩm trong cơ sở dữ liệu
                var product = objWebsiteBanHangEntities.Product.Find(id);
                if (product != null)
                {
                    // Kiểm tra số lượng trước khi giảm
                    if (product.soluong >= quantity)
                    {
                        product.soluong -= quantity;
                        objWebsiteBanHangEntities.SaveChanges();
                    }
                    else
                    {
                        // Xử lý khi số lượng không đủ
                        return Json(new { Message = "Sản phẩm không đủ số lượng", JsonRequestBehavior.AllowGet });
                    }
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thanh cong", JsonRequestBehavior.AllowGet });
           
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for(int i=0;i<cart.Count;i++)
            
                if (cart[i].Product.product_id.Equals(id))
                    return i;
            return -1;
        }
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.product_id == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"])-1;
            return Json(new { Message = "Thanh cong", JsonRequestBehavior.AllowGet });
        }
    }
}

Code/WebSiteQuanAo1/WebSiteQuanAo/WebSiteQuanAo/WebsiteBanHang/WebsiteBanHang/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Context;
using WebsiteBanHang.Models;

namespace WebsiteBanHang.Controllers
{
    public class PaymentController : Controller
    {
        WebsiteBanQuanAoEntities2 objWebsiteBanHangEntities = new WebsiteBanQuanAoEntities2();
        // GET: Payment
        public ActionResult Index()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                //lay thong tin gio hang tu bien session
                var lstCart = (List<CartModel>)Session["cart"];
                //gan du lieu cho order
                Orders objorder = new Orders();
                objorder.order_id = 3;
                objorder.user_id = 1;
                objorder.order_name = "DonHang-" + DateTime.Now.ToString("yyyyMMddHHmmss");
                objorder.product_id = 1;
                objorder.price=50000;
                objorder.status = 1;
                objorder.created = DateTime.Now;
              
                objWebsiteBanHangEntities.Orders.Add(objorder);
                //luu thong tin vao bang order
                objWebsiteBanHangEntities.SaveChanges();
                Product product1 = new Product();
                product1.soluong -= 1;
                //lay orderId vua moi tao de luu vao bang OrderDetail
                //int intOrderId = objorder.order_id;
                //List<OrderDetail> lstOrderDetail = new List<OrderDetail>();
                //foreach (var item in lstCart)
                //{
                //    OrderDetail obj = new OrderDetail();
                //    obj.Quantity = item.Quantity;
                //    obj.OrderId = intOrderId;
                //    obj.ProductId = item.Product.Id;
                //    lstOrderDetail.Add(obj);

                //}

                objWebsiteBanHangEntities.SaveChanges();
            }
            return View();
        }
    }
}

Code/WebSiteQuanAo1/WebSiteQuanAo/WebSiteQuanAo/WebsiteBanHang/WebsiteBanHang/Views/Cart/Index.cshtml
@model IEnumerable<WebsiteBanHang.Models.CartModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#removecart").click(function ()
        {
            var model = {};
            //lay id san pham
            model.Id = $("#productid").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Remove", "Cart")',
                data: JSON.stringify(model),
                dataType: "json",
                contentType: "application/json; charset=utf - 8",
                success: function () {
                    $('#CartCount').text(@Session["count"] -1);
                    $("#product-" + model.Id).remove();
                },
                error: function () {
                    alert("Loi trong khi them vao vo hang");
                }
            });
            return false;

            });
        });
</script>
<section class="section-content padding-y">
    <div class="container">

        <div class="row">
            <main class="col-md-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model!=null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr id="product-@item.Product.product_id">
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="~/Content/images/items/@item.Product.avatar" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="#" class="title text-dark">@item.Product.product_name</a>

                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <input type="text" value="@item.Quantity" />

                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                
                                                <input  class="price" type="number" value="@item.Product.price"/>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <input type="hidden" value="@item.Product.product_id" id="productid"/>
                                            <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a>
                                            
                                               
                                            <a href="#" class="btn btn-light" id="removecart"> Remove</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else {
                                <p>Khong co san pham trong gio hang</p>
                            
                            }



                        </tbody>
                    </table>

                    <div class="card-body border-top">

                        <a href="@Url.Action("Index","Payment")" class="btn btn-primary float-md-right"> Thanh Toán <i class="fa fa-chevron-right"></i> </a>
                        <a href="@Url.Action("Index","Home")" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Continue shopping </a>
                    </div>
                </div> <!-- card.// -->

            

            </main> <!-- col.// -->
           
        </div>

    </div> <!-- container .//  -->
</section>